// Generated by gencpp from file rokae_msgs/ExternalForce.msg
// DO NOT EDIT!


#ifndef ROKAE_MSGS_MESSAGE_EXTERNALFORCE_H
#define ROKAE_MSGS_MESSAGE_EXTERNALFORCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace rokae_msgs
{
template <class ContainerAllocator>
struct ExternalForce_
{
  typedef ExternalForce_<ContainerAllocator> Type;

  ExternalForce_()
    : force()
    , moment()  {
    }
  ExternalForce_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , moment(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _moment_type;
  _moment_type moment;





  typedef boost::shared_ptr< ::rokae_msgs::ExternalForce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_msgs::ExternalForce_<ContainerAllocator> const> ConstPtr;

}; // struct ExternalForce_

typedef ::rokae_msgs::ExternalForce_<std::allocator<void> > ExternalForce;

typedef boost::shared_ptr< ::rokae_msgs::ExternalForce > ExternalForcePtr;
typedef boost::shared_ptr< ::rokae_msgs::ExternalForce const> ExternalForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_msgs::ExternalForce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_msgs::ExternalForce_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokae_msgs::ExternalForce_<ContainerAllocator1> & lhs, const ::rokae_msgs::ExternalForce_<ContainerAllocator2> & rhs)
{
  return lhs.force == rhs.force &&
    lhs.moment == rhs.moment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokae_msgs::ExternalForce_<ContainerAllocator1> & lhs, const ::rokae_msgs::ExternalForce_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokae_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_msgs::ExternalForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_msgs::ExternalForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_msgs::ExternalForce_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "572f71e60f73d6a9e5c0b5d4c329a492";
  }

  static const char* value(const ::rokae_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x572f71e60f73d6a9ULL;
  static const uint64_t static_value2 = 0xe5c0b5d4c329a492ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_msgs/ExternalForce";
  }

  static const char* value(const ::rokae_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# force vector separated into force and moment\n"
"geometry_msgs/Vector3 force\n"
"geometry_msgs/Vector3 moment\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rokae_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.moment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExternalForce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_msgs::ExternalForce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokae_msgs::ExternalForce_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "moment: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.moment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_MSGS_MESSAGE_EXTERNALFORCE_H
