// Generated by gencpp from file rokae_msgs/JointPosVel.msg
// DO NOT EDIT!


#ifndef ROKAE_MSGS_MESSAGE_JOINTPOSVEL_H
#define ROKAE_MSGS_MESSAGE_JOINTPOSVEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokae_msgs
{
template <class ContainerAllocator>
struct JointPosVel_
{
  typedef JointPosVel_<ContainerAllocator> Type;

  JointPosVel_()
    : timestamp(0.0)
    , positions()
    , velocities()  {
    }
  JointPosVel_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , positions(_alloc)
    , velocities(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _positions_type;
  _positions_type positions;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocities_type;
  _velocities_type velocities;





  typedef boost::shared_ptr< ::rokae_msgs::JointPosVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_msgs::JointPosVel_<ContainerAllocator> const> ConstPtr;

}; // struct JointPosVel_

typedef ::rokae_msgs::JointPosVel_<std::allocator<void> > JointPosVel;

typedef boost::shared_ptr< ::rokae_msgs::JointPosVel > JointPosVelPtr;
typedef boost::shared_ptr< ::rokae_msgs::JointPosVel const> JointPosVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_msgs::JointPosVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_msgs::JointPosVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokae_msgs::JointPosVel_<ContainerAllocator1> & lhs, const ::rokae_msgs::JointPosVel_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.positions == rhs.positions &&
    lhs.velocities == rhs.velocities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokae_msgs::JointPosVel_<ContainerAllocator1> & lhs, const ::rokae_msgs::JointPosVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokae_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_msgs::JointPosVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_msgs::JointPosVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_msgs::JointPosVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deb4fb4efd7a8f0c7867baee56f1a9a5";
  }

  static const char* value(const ::rokae_msgs::JointPosVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeb4fb4efd7a8f0cULL;
  static const uint64_t static_value2 = 0x7867baee56f1a9a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_msgs/JointPosVel";
  }

  static const char* value(const ::rokae_msgs::JointPosVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is for joint postion and velocity accquire.\n"
"float64 timestamp\n"
"float64[] positions\n"
"float64[] velocities\n"
;
  }

  static const char* value(const ::rokae_msgs::JointPosVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.positions);
      stream.next(m.velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPosVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_msgs::JointPosVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokae_msgs::JointPosVel_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_MSGS_MESSAGE_JOINTPOSVEL_H
