controller_list:
  - name: fake_xmatepro7_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses per group
#  - group: xmatepro7
#    pose: home

  []