controller_list:
  - name: fake_rokae_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses per group
  - group: rokae_arm
    pose: init_pose